
# self.ui.mediaProgressSlider.sliderMoved.connect(self.set_position)
# self.ui.mediaVolumeSlider.sliderMoved.connect(self.set_volume)
# self.ui.mediaPlayBtn.clicked.connect(self.play_pause)
# self.ui.mediaNextBtn.clicked.connect(self.next)
# self.ui.mediaPreviousBtn.clicked.connect(self.previous)
# self.ui.seekForwardBtn.clicked.connect(lambda: self.seek(10000))
# self.ui.seekBackwardBtn.clicked.connect(lambda: self.seek(-10000))
# self.ui.mediaStopBtn.clicked.connect(self.stop)
# self.ui.mediaMuteBtn.clicked.connect(self.mute_unmute)
# self.ui.playSoundBtn.clicked.connect(self.mute_unmute)
# self.ui.mediaRepeatBtn.clicked.connect(self.toggle_repeat)
# self.ui.mediaShuffleBtn.clicked.connect(self.toggle_shuffle)
# self.ui.playbackSpeedCombobox.currentIndexChanged.connect(
#     self.set_playback_speed)
# self.ui.playerUndockBtn.clicked.connect(self.toggle_fullscreen)
# self.ui.mediaFolderBtn.clicked.connect(self.select_new_folder)
# self.ui.playerLockBtn.clicked.connect(self.lock_player)